# Generated by Django 4.0.4 on 2022-05-31 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fboard', '0005_alter_fboard_f_createdate_alter_fboard_f_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fboard',
            name='f_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 31, 14, 34, 26, 123673)),
        ),
        migrations.AlterField(
            model_name='fboard',
            name='f_updatedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 31, 14, 34, 26, 123673)),
        ),
    ]
