# Generated by Django 4.0.4 on 2022-05-27 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fboard',
            fields=[
                ('f_no', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.CharField(max_length=100)),
                ('f_title', models.CharField(max_length=1000)),
                ('f_content', models.TextField()),
                ('f_group', models.IntegerField(default=0)),
                ('f_step', models.IntegerField(default=0)),
                ('f_indent', models.IntegerField(default=0)),
                ('f_hit', models.IntegerField(default=1)),
                ('f_createdate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 27, 10, 6, 6, 933933))),
                ('f_updatedate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 27, 10, 6, 6, 933933))),
                ('f_file', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
